export const USERLOGINREQUEST="USERLOGINREQUEST"
export const USERLOGINSUCESSFUL="USERLOGINSUCESSFUL"
export const USERLOGINFAIL="USERLOGINFAIL"


export const USERSIGNUPREQUEST="USERSIGNUPREQUEST"
export const USERSIGNUPSUCESSFUL="USERSIGNUPSUCESSFUL"
export const USERSIGNUPFAIL="USERSIGNUPFAIL"