export const DEALERLOGINREQUEST="DEALERLOGINREQUEST"
export const DEALERLOGINSUCESSFUL="DEALERLOGINSUCESSFUL"
export const DEALERLOGINFAIL="DEALERLOGINFAIL"


export const DEALERSIGNUPREQUEST="DEALERSIGNUPREQUEST"
export const DEALERSIGNUPSUCESSFUL="DEALERSIGNUPSUCESSFUL"
export const DEALERSIGNUPFAIL="DEALERSIGNUPFAIL"