export const DEALERADDCARREQUEST="DEALERADDCARREQUEST"
export const DEALERADDCARSUCESSFUL="DEALERADDCARSUCESSFUL"
export const DEALERADDCARFAIL="DEALERADDCARFAIL"

export const DEALERFETCARREQUEST="DEALERFETCARREQUEST"
export const DEALERFETCARSUCESSFUL="DEALERFETCARSUCESSFUL"
export const DEALERFETCARFAIL="DEALERFETCARFAIL"


export const DEALERDELETECARREQUEST="DEALERDELETECARREQUEST"
export const DEALERDELETECARSUCESSFUL="DEALERDELETECARSUCESSFUL"
export const DEALERDELETECARFAIL="DEALERDELETECARFAIL"

export const DEALERUPDATENEWVALUECARREQUEST="DEALERUPDATENEWVALUECARREQUEST"
export const DEALERUPDATENEWVALUECARSUCESSFUL="DEALERUPDATENEWVALUECARSUCESSFUL"
export const DEALERUPDATENEWVALUECARFAIL="DEALERUPDATENEWVALUECARFAIL"


export const DEALERGETDETEALSCARREQUEST="DEALERGETDETEALSCARREQUEST"
export const DEALERGETDETEALSCARSUCESSFUL="DEALERGETDETEALSCARSUCESSFUL"
export const DEALERGETDETEALSCARFAIL="DEALERGETDETEALSCARFAIL"

export const DEALERUPDATECARREQUEST="DEALERUPDATECARREQUEST"
export const DEALERUPDATECARSUCESSFUL="DEALERUPDATECARSUCESSFUL"
export const DEALERUPDATECARFAIL="DEALERUPDATECARFAIL"